def armazenarStatus (jogador):
    lista = []
    lista.append(jogador.vida)
    lista.append(jogador.vidaMax)
    lista.append(jogador.ataque)
    lista.append(jogador.defesa)
    lista.append(jogador.classe)
    lista.append(jogador.nome)
    lista.append(jogador.critico)
    lista.append(jogador.inteligencia)
    lista.append(jogador.mana)
    lista.append(jogador.manaMax)
    lista.append(jogador.regenMana)
    lista.append(jogador.habilidades)
    lista.append(jogador.habilidadesDesc)
    lista.append(jogador.nome)
    lista.append(jogador.ouro)
    lista.append(jogador.caminhado)
    lista.append(jogador.artefatos)
    lista.append(jogador.artefatosDesc)
    lista.append(jogador.danoAumentado)
    lista.append(jogador.passar)
    lista.append(jogador.podeAgir)
    lista.append(jogador.criticoGarantido)
    lista.append(jogador.foiCritico)
    lista.append(jogador.dano)
    lista.append(jogador.danoReal)
    lista.append(jogador.acaoBonus)
    
    print(lista)